services:
  - type: web
    name: inventory-backend
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: DATABASE_URL
        sync: false # Set this in Render dashboard for security
    plan: free
    autoDeploy: true
    rootDir: .

  - type: static
    name: inventory-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: client/dist
    rootDir: client
    plan: free
    autoDeploy: true 